version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000
